.TH  tartos 1  "Apr 041, 2015" "tartos Version 1.0"
.UC 4

.SH "NAME"
tartos - TAR to shell script
.SH "SYNOPSIS"
.B tartos
[ \-\fBo\fP outfile ]
[ \-\fBO\fP outfile ]
.SH "DESCRIPTION"
.B tartos

The tartos script is a standalone bash shell script which binds different type of TAR archives 
to a single shell script (bash). This kind of approach is generally adopted to make a single 
install script from an existing tar archives with executable or installable software. It can 
be used to make a self extracting archive/installer which does some additional jobs like 
installing softwares, compared to the conventional tar archive files. The tartos script itself 
is written in bash and thus depends on it and on the package tar.

.SH "OPTIONS"
The command line options are:
.TP
.B -o outfile
Output directory where the script will install archive later
.TP
.B -O outfile
Output directory where the script will install archive later
.TP
.B -h
show help menu
.TP
.B --help
show help menu
.SH "EXAMPLES"
.B tartos

tartos archive script "command"

tartos archive script "command" \-o directory

tartos \-O directory archive script "command"

.SH "ADVANCED USE"
.B tartos

tartos archive scriptname "commands" \-o outputdir

1. It can take upto four arguments, the first argument is a tar archive, 

second one is the name of the target script file

and third one is custom command and the 4th argument is of type [\-o outdir]

[\-o outdir] can take any position as long as the sequence of the first three argument is maintained.

Ex1: tartos path_to_tar_file script_name_or_path command

Ex2: tartos archive script command \-o directory

Ex3: tartos \-O directory archive script command

\-o and \-O is equivalent 

2. It will ask for necessary arguments/info as it needs on the way.

3. Give commands inside quotation mark: double quotation is recommended

4. Best way of giving custom command is to write them in another script and put that script

as a command into tartos command input.

Ex: Enter custom command or script (if any): ./mycustomscript

if the path to the script contains space, use double quotes

.SH "BUGS"
Report bugs to <http://github.com/neurobin/tartos>
.SH "AUTHOR"
Jahidul Hamid
<http://github.com/neurobin>